name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ORG_PROJECT: NestTestProject
      DEPLOY_ENV: NestTestProjectEnvironment
    steps:

    - uses: actions/checkout@v2
    - name: Install dependencies

      run: npm i

    - name: Lint the codebase
      run: npm lint

    - name: Test our code
      run: npm run test

    - name: Login
      run: npx warp login --api-key=4iYzFr0EdoGwLB1RYaseFq

    - name: Deploy
      run: npx warp deploy --project ${ORG_PROJECT} --env ${DEPLOY_ENV}
